# Generated by Django 4.2.2 on 2023-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do_item_title', models.CharField(max_length=50)),
                ('to_do_due_date', models.DateTimeField()),
                ('to_do_submitted_date', models.DateTimeField(auto_now_add=True)),
                ('to_do_description', models.TextField(blank=True, default='no description', max_length=200)),
                ('to_do_list_id', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['to_do_due_date'],
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do_list_title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
